// ============================================================
// internal/collector/ebpf_loader.go
// Loads the compiled eBPF program, attaches tracepoints,
// and reads events from the ring buffer into a Go channel.
// ============================================================
package collector

import (
	"bytes"
	"encoding/binary"
	"fmt"
	"log"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/cilium/ebpf/rlimit"
)

// SentinelObjects holds all eBPF maps and programs after loading.
// Generated by `bpf2go` from sentinel.bpf.c — see generate.go.
// For manual loading we use a generic struct here.
type sentinelObjects struct {
	Programs struct {
		TraceExecve  *ebpf.Program `ebpf:"trace_execve"`
		TraceOpenat  *ebpf.Program `ebpf:"trace_openat"`
		TraceConnect *ebpf.Program `ebpf:"trace_connect"`
		TraceClone   *ebpf.Program `ebpf:"trace_clone"`
	}
	Maps struct {
		Events        *ebpf.Map `ebpf:"events"`
		SyscallCounts *ebpf.Map `ebpf:"syscall_counts"`
	}
}

// Collector reads BPF events and pushes them to a channel.
type Collector struct {
	EventCh chan BpfEvent
	stopCh  chan struct{}
}

// NewCollector creates a Collector with a buffered event channel.
func NewCollector(bufSize int) *Collector {
	return &Collector{
		EventCh: make(chan BpfEvent, bufSize),
		stopCh:  make(chan struct{}),
	}
}

// Run loads the eBPF object file, attaches all tracepoints, and reads
// the ring buffer until ctx is cancelled or SIGINT/SIGTERM is received.
//
// objPath — path to the compiled sentinel.bpf.o file.
func (c *Collector) Run(objPath string) error {
	// ── 1. Remove memory lock limit (required for BPF maps) ──
	if err := rlimit.RemoveMemlock(); err != nil {
		return fmt.Errorf("remove memlock: %w", err)
	}

	// ── 2. Load the compiled eBPF object ─────────────────────
	spec, err := ebpf.LoadCollectionSpec(objPath)
	if err != nil {
		return fmt.Errorf("load collection spec: %w", err)
	}

	coll, err := ebpf.NewCollection(spec)
	if err != nil {
		return fmt.Errorf("new collection: %w", err)
	}
	defer coll.Close()

	// ── 3. Attach tracepoints ─────────────────────────────────
	hooks := []struct {
		group   string
		name    string
		progKey string
	}{
		{"syscalls", "sys_enter_execve", "trace_execve"},
		{"syscalls", "sys_enter_openat", "trace_openat"},
		{"syscalls", "sys_enter_connect", "trace_connect"},
		{"syscalls", "sys_enter_clone", "trace_clone"},
	}

	var links []link.Link
	for _, h := range hooks {
		prog, ok := coll.Programs[h.progKey]
		if !ok {
			return fmt.Errorf("program %q not found in eBPF object", h.progKey)
		}
		l, err := link.Tracepoint(h.group, h.name, prog, nil)
		if err != nil {
			return fmt.Errorf("attach tracepoint %s/%s: %w", h.group, h.name, err)
		}
		links = append(links, l)
		log.Printf("✅ Attached tracepoint: %s/%s", h.group, h.name)
	}
	defer func() {
		for _, l := range links {
			l.Close()
		}
	}()

	// ── 4. Open ring buffer reader ────────────────────────────
	eventsMap, ok := coll.Maps["events"]
	if !ok {
		return fmt.Errorf("ring buffer map 'events' not found")
	}

	rd, err := ringbuf.NewReader(eventsMap)
	if err != nil {
		return fmt.Errorf("open ring buffer reader: %w", err)
	}
	defer rd.Close()

	// ── 5. Handle SIGINT / SIGTERM gracefully ─────────────────
	sig := make(chan os.Signal, 1)
	signal.Notify(sig, syscall.SIGINT, syscall.SIGTERM)
	go func() {
		<-sig
		log.Println("Signal received — closing ring buffer reader")
		rd.Close()
		close(c.stopCh)
	}()

	log.Println("🔍 SentinelGo: listening for kernel events…")

	// ── 6. Read loop ──────────────────────────────────────────
	for {
		record, err := rd.Read()
		if err != nil {
			// rd.Close() was called — this is a clean shutdown
			if err == ringbuf.ErrClosed {
				return nil
			}
			log.Printf("ring buffer read error: %v", err)
			continue
		}

		var event BpfEvent
		if err := binary.Read(bytes.NewReader(record.RawSample), binary.LittleEndian, &event); err != nil {
			log.Printf("decode BPF event: %v", err)
			continue
		}

		// Non-blocking send — if the pipeline is full, drop oldest behavior
		// is handled by the buffered channel.
		select {
		case c.EventCh <- event:
		default:
			// Channel full — drop silently (avoid blocking the ring buffer reader)
		}
	}
}

// ── Stub collector for testing without a real kernel ─────────
// Returns fake events so the rest of the pipeline can be tested
// on any machine (e.g., macOS, CI, VMs without BPF support).
func (c *Collector) RunStub() {
	log.Println("🧪 Running STUB collector (no real eBPF — for testing only)")

	syscalls := []SyscallID{SyscallExecve, SyscallOpenat, SyscallConnect, SyscallClone}
	procs := []string{"bash", "curl", "python3", "sshd", "cat", "wget"}
	files := []string{"/bin/bash", "/etc/passwd", "/tmp/data", "/home/user/.ssh/id_rsa", "/dev/null"}

	ticker := time.NewTicker(200 * time.Millisecond)
	defer ticker.Stop()

	i := 0
	for {
		select {
		case <-c.stopCh:
			return
		case <-ticker.C:
			proc := procs[i%len(procs)]
			sc := syscalls[i%len(syscalls)]
			file := files[i%len(files)]

			var comm [16]byte
			var fname [64]byte
			copy(comm[:], proc)
			copy(fname[:], file)

			c.EventCh <- BpfEvent{
				PID:         uint32(1000 + i),
				PPID:        1000,
				Comm:        comm,
				Filename:    fname,
				SyscallID:   sc,
				TimestampNS: uint64(time.Now().UnixNano()),
			}
			i++
		}
	}
}
